### ISSUE TITLE
アプリが落ちる

### ISSUE THREAD

**Issue by y-ogawara** [y-ogawara/myRobotController#5]
## 問題
アプリが落ちる

## おかしい疑惑がある部分
接続後、切断されて死ぬ

**Comment by Dai1678** [comment]
ホワイトアウトしてた端末は初期化・再ビルドして表示されるようになった

**Comment by y-ogawara** [comment]
暫定的にclose

**Comment by Dai1678** [comment]
Bluetooth接続失敗が連続して起きてから、アプリを再起動したときに発生することが多いかも
