### ISSUE TITLE
持って走らせると動くけど、置くと動かない

### ISSUE THREAD

**Issue by y-ogawara** [y-ogawara/myRobotController#7]
### 問題
持って走らせると動くけど、置くと動かない

### おかしい疑惑がある部分
始め1秒くらい加速させる？

**Comment by Dai1678** [comment]
考えられる原因
・電池残量がすくない
・ギアの不良
・通信がうまくいってない

**Comment by Dai1678** [comment]
電池残量が少ないことが問題だと思います
